# Generated by Django 4.2 on 2023-04-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.FileField(blank=True, null=True, upload_to='', verbose_name='foto de publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('like', models.TextField(blank=True, null=True, verbose_name='comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='', verbose_name='video de publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Viajero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefono viajero')),
                ('alias', models.CharField(blank=True, max_length=20, null=True, verbose_name='nombre de usuario')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='', verbose_name='foto de perfil')),
                ('sexo', models.CharField(blank=True, null=True, verbose_name='sexo del viajero')),
                ('fecha_nacimiento', models.DateTimeField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('fecha_alta', models.DateTimeField(blank=True, null=True, verbose_name='fecha de alta')),
                ('conectado', models.BooleanField(blank=True, null=True, verbose_name='estado del viajero')),
                ('verificado', models.BooleanField(blank=True, null=True, verbose_name='cuenta verificada')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, null=True, verbose_name='texto publicado')),
                ('tiempo', models.DateTimeField(default=django.utils.timezone.now)),
                ('like_activo', models.BooleanField(verbose_name='like acitvo o no')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptrip.foto')),
                ('viajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptrip.viajero')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptrip.video')),
            ],
        ),
    ]
