# Generated by Django 4.2 on 2023-04-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptrip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='foto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicacion_foto', to='apptrip.foto'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='viajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicacion_viajero', to='apptrip.viajero'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='publicacion_video', to='apptrip.video'),
        ),
        migrations.CreateModel(
            name='Seguidor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seguidor_viajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguidor_viajero', to='apptrip.viajero')),
                ('viajero_seguido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seguido_viajero', to='apptrip.viajero')),
            ],
        ),
        migrations.CreateModel(
            name='Seguido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('seguidor_viajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajero_seguidor', to='apptrip.viajero')),
                ('viajero_seguido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajero_seguido', to='apptrip.viajero')),
            ],
        ),
    ]
