# Generated by Django 4.2 on 2023-04-26 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptrip', '0002_alter_publicacion_foto_alter_publicacion_viajero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiendo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(blank=True, max_length=30, null=True, verbose_name='direccion_alojamiento')),
                ('poblacion', models.TextField(blank=True, max_length=20, null=True, verbose_name='poblacion_alojamiento')),
                ('provincia', models.TextField(blank=True, max_length=20, null=True, verbose_name='provincia_alojamiento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_alojamiento', verbose_name='Foto_alojamiento')),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dueño_vivienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
