# Generated by Django 4.2 on 2023-04-26 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apptrip', '0003_alojamiendo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(blank=True, max_length=30, null=True, verbose_name='direccion_alojamiento')),
                ('poblacion', models.CharField(blank=True, max_length=20, null=True, verbose_name='poblacion_alojamiento')),
                ('provincia', models.CharField(blank=True, max_length=20, null=True, verbose_name='provincia_alojamiento')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_alojamiento', verbose_name='Foto_alojamiento')),
                ('cp', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_alta', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dueño_vivienda', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Alojamiento_prestado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha de inicio ')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('realizado', models.BooleanField(blank=True, null=True, verbose_name='prestado')),
                ('reservado', models.BooleanField(blank=True, null=True, verbose_name='reservado0')),
                ('duracion', models.TimeField(blank=True, null=True, verbose_name='duracion')),
                ('alojamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vivienda_prestada', to='apptrip.alojamiento')),
                ('viajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajero_alojado', to='apptrip.viajero')),
            ],
        ),
        migrations.CreateModel(
            name='Prestar_alojamiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('realizado', models.BooleanField(blank=True, null=True, verbose_name='prestado')),
                ('reservado', models.BooleanField(blank=True, null=True, verbose_name='reservado0')),
                ('duracion', models.TimeField(blank=True, null=True, verbose_name='duracion')),
                ('alojamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vivienda_prestar', to='apptrip.alojamiento')),
                ('viajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='viajero_presta', to='apptrip.viajero')),
            ],
        ),
        migrations.DeleteModel(
            name='Alojamiendo',
        ),
    ]
